name: validate-portfolio
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11', cache: pip }
      - name: Install Genesis CI requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ASI-T/GENESIS/CI/requirements.txt
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          fi
      - name: Path grammar & UTCS headers
        run: python ASI-T/GENESIS/SCRIPTS/check_paths.py
      - name: Schema validation
        run: python ASI-T/GENESIS/SCRIPTS/validate_schemas.py
      - name: FCR enforcement
        env:
          GITHUB_PR_BODY: ${{ github.event.pull_request.body }}
        run: python ASI-T/GENESIS/SCRIPTS/fcr_enforcer.py
      - name: Evidence linting
        run: python ASI-T/GENESIS/SCRIPTS/evidence_lint.py
      - name: Legacy portfolio checks
        run: |
          make validate || true
      - name: Canonical naming validation
        run: |
          python tools/validate_paths.py